services:
  db_fonte:
    image: postgres:15
    container_name: db_fonte
    environment:
      POSTGRES_DB: fonte
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" 
    volumes:
      - db_fonte_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./db/povoamento.sql:/docker-entrypoint-initdb.d/02_povoamento.sql

  db_alvo:
    image: postgres:15
    container_name: db_alvo
    environment:
      POSTGRES_DB: alvo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - db_alvo_data:/var/lib/postgresql/data

  api_fonte:
    build: 
      context: ./api
      dockerfile: Dockerfile.api

    depends_on:
      - db_fonte
    environment:
      - DATABASE_URL=postgresql://user:password@db_fonte:5432/fonte
    volumes:
      - ./api:/app
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"

  db_init:
    build: 
      context: ./etl
      dockerfile: Dockerfile.etl
    depends_on:
      - db_alvo
    environment:
      - DATABASE_URL=postgresql://user:password@db_alvo:5432/alvo
    volumes:
      - ./etl:/app
    working_dir: /app
    command: ["python", "create_tables.py"]

  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile.etl
    depends_on:
      - db_init
      - api_fonte
      - db_alvo
    environment:
      - API_URL=http://api_fonte:8000/data/
      - DATABASE_URL=postgresql://user:password@db_alvo:5432/alvo
    volumes:
      - ./etl:/app
    command: ["python", "etl.py", "01-01-2025", "wind_speed", "power"]



volumes:
  db_fonte_data:
  db_alvo_data:
